$(".hero").append("<div id=\"optimizely_706143523\">...</div>");
$("#optimizely_706143523").html("<br><br>NEW: Mobile app A/B testing is now available at all plan levels. Learn more");
$("#optimizely_706143523").html("<br><br>Optimizely for iOS beta is now included for a limited time at all plan levels. Learn more&nbsp;");
$("#optimizely_706143523").html("<br><br>Optimizely for iOS beta is now included for a limited time at all plan levels. Learn more »");
$("#optimizely_706143523").replaceWith("<div id=\"optimizely_706143523\"><br><br>Optimizely for iOS beta is now included for a limited time at all plan levels. <a>Learn more »</a></div>");
$("#optimizely_706143523").replaceWith("<div id=\"optimizely_706143523\"><br><br>Optimizely for iOS beta is available for a limited time at all plan levels. <a>Learn more »</a></div>");
$("#optimizely_706143523").replaceWith("<div id=\"optimizely_706143523\"><br><br>Optimizely for iOS beta is now available for a limited time at all plan levels. <a>Learn more »</a></div>");
$("#optimizely_706143523").html("<br><br>NEW: Get fast and scalable A/B testing for iOS apps.&nbsp;<a>Learn more »</a>");
$("#optimizely_706143523").html("<br><br>A/B testing for iOS apps is here.&nbsp;<a>Learn more »</a>");
$("#optimizely_706143523").replaceWith("<div id=\"optimizely_706143523\"><br><br>A/B testing for mobile apps is here.&nbsp;<a>Learn more »</a></div>");
$("#optimizely_706143523").html("<br><br>Mobile app A/B testing is here.&nbsp;<a>Learn more »</a>");