$("h1.headline > span:eq(0)").html("Optimizely");
$("h1.headline").html("\n          <span>Optimizely</span> for iOS Beta");
$("h2.headline").css({"display":"none", "visibility":""});
$(".subheadline").html("\n          Request Access to Beta");
$(".notify-me").html("\n              Request Access");
$(".subheadline").html("\n          Request Access to Developer-only Beta Release");
$("h1.headline").html("\n          <span>Optimizely</span> for iOS Private Beta");
$(".subheadline").html("\n          Request Access to Beta Release.");
$("h1.headline").html("\n          <span>Optimizely</span> for iOS Private Beta.");
$(".subheadline").html("\n          Request Access to Beta.");